const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Deploying VotingContract...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log(`Deploying with account: ${deployer.address}`);
  console.log(`Account balance: ${hre.ethers.utils.formatEther(await deployer.getBalance())} ETH\n`);

  // Deploy the contract
  const VotingContract = await hre.ethers.getContractFactory("VotingContract");
  const votingContract = await VotingContract.deploy();
  await votingContract.deployed();

  console.log(`✅ VotingContract deployed to: ${votingContract.address}\n`);

  // ─── Save ABI + Address to context/constants.js ───────────────────────────
  const contractArtifact = await hre.artifacts.readArtifact("VotingContract");

  const constantsContent = `// Auto-generated by deploy script — DO NOT EDIT MANUALLY

export const VOTING_CONTRACT_ADDRESS = "${votingContract.address}";

export const VOTING_CONTRACT_ABI = ${JSON.stringify(contractArtifact.abi, null, 2)};
`;

  const constantsPath = path.join(__dirname, "..", "context", "constants.js");
  fs.writeFileSync(constantsPath, constantsContent);
  console.log(`📄 ABI and address written to: context/constants.js`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
